import axios from "axios";

const getDate = new Date().toISOString();

export const generateSitemap = async () => {
  const { data } = await axios.get("https://api.loelblog.com/post");
  const DOMAIN = "https://loelblog.com";

  const newPostsSiteMap = await data.map((post) => makeSiteMapItemXml(` ${DOMAIN}/post/${post.id}`, 1));

  return wrapSiteMap(newPostsSiteMap);
};

function makeSiteMapItemXml(url, priority) {
  return `<url>
        <loc>${url}</loc>
        <lastmod>${getDate}</lastmod>
        <changefreq>weekly</changefreq>
        <priority>${priority}</priority>
    </url>`;
}

function wrapSiteMap(body) {
  return `<?xml version="1.0" encoding="utf-8"?>
    <!--Generated by Screaming Frog SEO Spider 9.4-->
    <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
        ${body}
    </urlset>`;
}
